-- LOCAL VARIABLES
DECLARE @SECURITYROLESYSUSERRECID BIGINT
DECLARE @SECURITYROLESYSADMINRECID BIGINT
DECLARE @SECURITYUSERROLESYSUSERRECID BIGINT
DECLARE @SECURITYUSERROLESYSADMINRECID BIGINT
DECLARE @USERRECID BIGINT
DECLARE @SECURITYROLESYSADMIN NVARCHAR(10)
DECLARE @SECURITYROLESYSUSER NVARCHAR(10)


-- SET LOCAL VARIABLES
SET @SECURITYROLESYSADMIN = '-SYSADMIN-'
SET @SECURITYROLESYSUSER = 'SYSTEMUSER'

SELECT @USERRECID = T1.RECID FROM [dbo].[USERINFO] T1 WHERE T1.ID = @Id
SELECT @SECURITYROLESYSUSERRECID = T1.RECID  FROM [dbo].[SECURITYROLE] T1 WHERE T1.AOTNAME = @SECURITYROLESYSUSER
SELECT @SECURITYROLESYSADMINRECID = T1.RECID  FROM [dbo].[SECURITYROLE] T1 WHERE T1.AOTNAME = @SECURITYROLESYSADMIN
SELECT @SECURITYUSERROLESYSUSERRECID = T1.RECID FROM [dbo].[SECURITYUSERROLE] T1 WHERE T1.USER_ = @ID AND   T1.SECURITYROLE = @SECURITYROLESYSUSERRECID
SELECT @SECURITYUSERROLESYSADMINRECID = T1.RECID FROM [dbo].[SECURITYUSERROLE] T1 WHERE T1.USER_ = @ID AND   T1.SECURITYROLE = @SECURITYROLESYSADMINRECID


-- CREATE NEW USER (IF DOESN'T EXIST)
IF (@USERRECID IS NULL)
	BEGIN
	INSERT INTO [dbo].[USERINFO]
				([ID]
				,[NAME]
				,[ENABLE]
				,[NETWORKDOMAIN]
				,[NETWORKALIAS]
				,[SID]
				,[COMPANY]
				,[LANGUAGE]
				,[HELPLANGUAGE]
				,[IDENTITYPROVIDER]
				,[DEFAULTPARTITION]		   
				,[ACCOUNTTYPE]
				,[RECVERSION]
				,[PARTITION]
				,[RECID])
			VALUES
				(
					@Id,
					@Name,
					@Enabled,
					@Provider,
					@Email,
					@SID,
					@Company,
					@Language,
					@Language,
					@Provider,
					1,			
					2,			
					1,
					(SELECT TOP 1 [PARTITION] FROM [dbo].[USERINFO]),
					(SELECT MAX(RecId) FROM [dbo].[USERINFO]) + 1
				)
	END
	

-- GRANT SYSTEM USER ROLE
IF (@SECURITYUSERROLESYSUSERRECID IS NULL)
	BEGIN
	INSERT INTO [dbo].[SECURITYUSERROLE]
			   ([USER_]
			   ,[SECURITYROLE]
			   ,[ASSIGNMENTSTATUS]
			   ,[ASSIGNMENTMODE]
			   ,[RECVERSION]
			   ,[PARTITION]
			   ,[RECID])
		 VALUES
			   (
					@Id,
					 @SECURITYROLESYSUSERRECID, 
					1,
					1, 
					1,
					(SELECT TOP 1 PARTITION FROM [dbo].[SECURITYUSERROLE]),
					(SELECT MAX(RecId) FROM [dbo].[SECURITYUSERROLE]) + 1
			   )
	END


-- GRANT SYSTEM ADMIN ROLE
IF (@SECURITYUSERROLESYSADMINRECID IS NULL)
	BEGIN
	INSERT INTO [dbo].[SECURITYUSERROLE]
			   ([USER_]
			   ,[SECURITYROLE]
			   ,[ASSIGNMENTSTATUS]
			   ,[ASSIGNMENTMODE]
			   ,[RECVERSION]
			   ,[PARTITION]
			   ,[RECID])
		 VALUES
			   (
				@Id,
				@SECURITYROLESYSADMINRECID, 
				1,
				1, 
				1,
				(SELECT TOP 1 PARTITION FROM [dbo].[SECURITYUSERROLE]),
				(SELECT MAX(RecId) FROM [dbo].[SECURITYUSERROLE]) + 1
			   )
	END