DECLARE @Id NVARCHAR(50)
SET @Id = (SELECT ID FROM dbo.USERINFO WHERE [NETWORKALIAS] = @Email AND [ID] != 'ADMIN')

DELETE dbo.SECURITYUSERROLE
WHERE USER_ = @Id

DELETE dbo.USERINFO
WHERE [NETWORKALIAS] = @Email AND [ID] != 'ADMIN'