/*Variable input @Id */
DROP TABLE IF EXISTS #TempSecurityUserRole
DROP TABLE IF EXISTS #TempRecIds

BEGIN TRANSACTION

SET NOCOUNT ON;

DECLARE @TableId AS int
        ,@RecId AS bigint
		,@AdminUserId as NVARCHAR(40) = 'Admin'
		,@InitialPartionKey as nvarchar(10) = 'initial'


SELECT 
	@Id as USER_,
	SECURITYUSERROLE.SECURITYROLE,
	SECURITYUSERROLE.ASSIGNMENTSTATUS,
	SECURITYUSERROLE.ASSIGNMENTMODE,
	SECURITYUSERROLE.VALIDFROM,
	SECURITYUSERROLE.VALIDFROMTZID,
	SECURITYUSERROLE.VALIDTO,
	SECURITYUSERROLE.VALIDTOTZID,
	SECURITYUSERROLE.PARTITION
INTO #TempSecurityUserRole
FROM SECURITYUSERROLE
JOIN [PARTITIONS] ON [PARTITIONS].Recid = SECURITYUSERROLE.PARTITION
WHERE [User_] = @AdminUserId
	AND PARTITIONKEY = @InitialPartionKey


INSERT INTO SECURITYUSERROLE (
	USER_,
	SECURITYROLE,
	ASSIGNMENTSTATUS,
	ASSIGNMENTMODE,
	VALIDFROM,
	VALIDFROMTZID,
	VALIDTO,
	VALIDTOTZID,
	PARTITION
)
SELECT * FROM #TempSecurityUserRole

DROP TABLE #TempSecurityUserRole
/* DROP TABLE #TempRecIds 
*/

commit TRANSACTION

Declare @AdminSecurityRoleCount as int

SELECT @AdminSecurityRoleCount = count(1) 
FROM SECURITYUSERROLE 
JOIN [PARTITIONS] ON [PARTITIONS].Recid = SECURITYUSERROLE.PARTITION
WHERE [User_] = @AdminUserId
AND PARTITIONKEY = @InitialPartionKey

Declare @ImportSecurityRoleCount as int

SELECT @ImportSecurityRoleCount = count(1) 
FROM SECURITYUSERROLE 
JOIN [PARTITIONS] ON [PARTITIONS].Recid = SECURITYUSERROLE.PARTITION
WHERE [User_] = @Id
AND PARTITIONKEY =  @InitialPartionKey

SET Nocount OFF;

select @AdminSecurityRoleCount - @ImportSecurityRoleCount